### ISSUE TITLE
[R-Forge #1592] Setting a non-existent column to NULL changes the last column's name.

### ISSUE THREAD

**Issue by joshuaulrich** [joshuaulrich/xts#45]
Submitted by: Leon Baum
Assigned to: Nobody
[R-Forge link](http://r-forge.r-project.org/tracker/index.php?func=detail&aid=1592&group_id=118&atid=516)

The following example demonstrates the bug:

> test <- xts(data.frame(x=1:5, y=5:1), order.by=Sys.time() + 1:5)
> test
                    x y
2011-09-16 20:43:00 1 5
2011-09-16 20:43:01 2 4
2011-09-16 20:43:02 3 3
2011-09-16 20:43:03 4 2
2011-09-16 20:43:04 5 1
> test$z <- NULL
> test
                    x z
2011-09-16 20:43:00 1 5
2011-09-16 20:43:01 2 4
2011-09-16 20:43:02 3 3
2011-09-16 20:43:03 4 2
2011-09-16 20:43:04 5 1

Note that the 2nd column has had its name changed from 'y' to 'z'. It should not have changed.

**Comment by joshuaulrich** [comment]
This is a bug in zoo.  xts does not provide a `$<-.xts` method, so `$<-.zoo` is dispatched. That said, this bug was fixed in r999 in zoo.

**Comment by MortenGrum** [comment]
I'm still getting this error with R version 3.5.3, xts_0.11-2 and zoo_1.8-4. 
Or at least I'm guessing this is the same error?

**My reproduction:**
```
library(xts)
y = xts( rnorm(5), Sys.time() - seq(from=10*300, length.out = 5, by=-300) )
names(y) = c("C1")
y$C2 = 2*y$C1*y$C1
y
y$C3 = xts(NULL, order.by = index(y))
y
```
Output from the ys:
```
                            C1        C2
2019-03-15 09:33:02 -0.5812749 0.6757610
2019-03-15 09:38:02 -1.3912957 3.8714077
2019-03-15 09:43:02  1.3388054 3.5848000
2019-03-15 09:48:02 -0.4506790 0.4062231
2019-03-15 09:53:02  0.6101158 0.7444826

                            C1        C3
2019-03-15 09:33:02 -0.5812749 0.6757610
2019-03-15 09:38:02 -1.3912957 3.8714077
2019-03-15 09:43:02  1.3388054 3.5848000
2019-03-15 09:48:02 -0.4506790 0.4062231
2019-03-15 09:53:02  0.6101158 0.7444826

```

If it is a zoo error, I am not sure how I would reproduce this in zoo allone.

**Comment by joshuaulrich** [comment]
Thanks for the report!  Here's an example using only zoo:

```r
library(zoo)
y <- zoo(matrix(1:5), Sys.time() - seq(from=10*300, length.out = 5, by=-300) )
names(y) <- c("C1")
y$C2 <- 2*y$C1*y$C1
y
#                     C1 C2
# 2019-03-15 03:57:54  1  2
# 2019-03-15 04:02:54  2  8
# 2019-03-15 04:07:54  3 18
# 2019-03-15 04:12:54  4 32
# 2019-03-15 04:17:54  5 50
y$C3 <- zoo(NULL, order.by = index(y))
y
#                     C1 C3
# 2019-03-15 03:57:54  1  2
# 2019-03-15 04:02:54  2  8
# 2019-03-15 04:07:54  3 18
# 2019-03-15 04:12:54  4 32
# 2019-03-15 04:17:54  5 50
```

The bug in this issue was triggered by `y$C3 <- NULL`.  This is a slightly different issue (setting a column to a zero-width object), but I'll make sure it gets fixed in zoo.

**Comment by joshuaulrich** [comment]
Thanks to Achim, this is now fixed in zoo (r1144, version 1.8-6).
